package com.ovi.handoff.core

import com.ovi.handoff.shared.protocol.SignatureAlgorithm
import java.io.File
import java.security.KeyFactory
import java.security.KeyPair
import java.security.PrivateKey
import java.security.PublicKey
import java.security.Signature
import java.security.spec.PKCS8EncodedKeySpec
import java.security.spec.X509EncodedKeySpec
import java.util.Base64

/**
 * The desktop's Ed25519 identity, plus verification of the phone's signatures.
 *
 * Two things changed from the original: the private key file is now restricted to the current user
 * (it was written with default permissions, readable by any other local account), and this class can
 * now *verify* as well as sign. Verification is the half that was missing entirely, which is why an
 * unsigned decision used to be accepted without question.
 */
public class KeyStoreManager(private val keyDir: File) {

    private val pubFile = File(keyDir, "device.pub")
    private val privFile = File(keyDir, "device.priv")

    public fun getOrGenerateKeyPair(): KeyPair {
        if (pubFile.exists() && privFile.exists()) {
            return loadKeyPair()
        }
        return generateAndSaveKeyPair()
    }

    private fun generateAndSaveKeyPair(): KeyPair {
        val generator = java.security.KeyPairGenerator.getInstance(ALGORITHM)
        val pair = generator.generateKeyPair()

        SecureFiles.writeSecureBytes(pubFile, pair.public.encoded)
        SecureFiles.writeSecureBytes(privFile, pair.private.encoded)

        return pair
    }

    private fun loadKeyPair(): KeyPair {
        // Re-assert the permissions on every load: a key generated by an older build is still 0644.
        SecureFiles.restrictToOwner(privFile, directory = false)

        val factory = KeyFactory.getInstance(ALGORITHM)
        val publicKey = factory.generatePublic(X509EncodedKeySpec(pubFile.readBytes()))
        val privateKey = factory.generatePrivate(PKCS8EncodedKeySpec(privFile.readBytes()))
        return KeyPair(publicKey, privateKey)
    }

    public fun sign(data: ByteArray, privateKey: PrivateKey): ByteArray {
        val signature = Signature.getInstance(ALGORITHM)
        signature.initSign(privateKey)
        signature.update(data)
        return signature.sign()
    }

    public companion object {
        private const val ALGORITHM = "Ed25519"

        /** Maps a signature algorithm name to the `KeyFactory` algorithm that parses its keys. */
        private fun keyFactoryAlgorithm(signatureAlgorithm: String): String = when (signatureAlgorithm) {
            SignatureAlgorithm.ECDSA_P256_SHA256 -> "EC"
            else -> "Ed25519"
        }

        /**
         * Decodes a base64url (or standard base64) X.509 public key, or null when malformed.
         *
         * [algorithm] is the signature algorithm the peer announced, not the key type, because that
         * is what travels in `PairHello`.
         */
        @JvmStatic
        @JvmOverloads
        public fun decodePublicKey(
            encoded: String?,
            algorithm: String = SignatureAlgorithm.ED25519
        ): PublicKey? {
            if (encoded.isNullOrBlank()) return null
            val bytes = decodeBase64(encoded) ?: return null
            return runCatching {
                KeyFactory.getInstance(keyFactoryAlgorithm(algorithm)).generatePublic(X509EncodedKeySpec(bytes))
            }.getOrNull()
        }

        /**
         * Verifies [signatureBase64] over [data] with [publicKey].
         *
         * Returns false rather than throwing on any malformed input, so a hostile frame cannot take
         * the daemon down and cannot be distinguished from an ordinary bad signature.
         */
        @JvmStatic
        @JvmOverloads
        public fun verify(
            data: ByteArray,
            signatureBase64: String?,
            publicKey: PublicKey?,
            algorithm: String = SignatureAlgorithm.ED25519
        ): Boolean {
            if (publicKey == null || signatureBase64.isNullOrBlank()) return false
            val signatureBytes = decodeBase64(signatureBase64) ?: return false
            return runCatching {
                val signature = Signature.getInstance(algorithm)
                signature.initVerify(publicKey)
                signature.update(data)
                signature.verify(signatureBytes)
            }.getOrDefault(false)
        }

        public fun encodePublicKey(publicKey: PublicKey): String =
            Base64.getUrlEncoder().withoutPadding().encodeToString(publicKey.encoded)

        public fun encodeSignature(signature: ByteArray): String =
            Base64.getUrlEncoder().withoutPadding().encodeToString(signature)

        private fun decodeBase64(value: String): ByteArray? {
            val trimmed = value.trim()
            // Accept both alphabets: the QR payload is url-safe, but a hand-copied key may not be.
            return runCatching { Base64.getUrlDecoder().decode(trimmed) }.getOrNull()
                ?: runCatching { Base64.getDecoder().decode(trimmed) }.getOrNull()
                ?: runCatching { Base64.getMimeDecoder().decode(trimmed) }.getOrNull()
        }
    }
}
